### ISSUE TITLE
fails to build on OmniOS using Clang 13 and 14

### ISSUE THREAD

**Issue by infrastation** [the-tcpdump-group/tcpslice#14]
```text
$ uname -a
SunOS tcpdump 5.11 omnios-r151042-7577932f27 i86pc i386 i86pc

$ clang-13 --version
OmniOS/151042 clang version 13.0.1
Target: x86_64-pc-solaris2.11
Thread model: posix
InstalledDir: /opt/ooce/bin

$ clang-14 --version
OmniOS/151042 clang version 14.0.0
Target: x86_64-pc-solaris2.11
Thread model: posix
InstalledDir: /opt/ooce/bin

$ gmake -s clean
$ gmake -s CFLAGS=-Werror
clang-14: error: '-fuse-ld=' taking a path is deprecated; use '--ld-path=' instead [-Werror,-Wfuse-ld-path]
gmake: *** [Makefile:129: tcpslice] Error 1
```

**Comment by infrastation** [comment]
For reference, building using Clang 14 works on other OSes (e.g. FreeBSD and NetBSD).

**Comment by citrus-it** [comment]
I think this is actually a problem with the clang packages on OmniOS - those warnings show up even when building clang with itself. I've spoken to the person who maintains clang and he is going to update the packages.

I'll post here once they are updated and hopefully that will resolve the problem you're seeing.

**Comment by infrastation** [comment]
Thank you for looking into this Andy.

**Comment by citrus-it** [comment]
I've updated the OmniOS builder to the release candidate for the upcoming r151044 release, and installed updated clang packages which should fix this (there will be a PR to update the stable releases in the next day or two).

As a bonus there are some extra compilers there:

```
root@tcpdump:~# pkg list '*/clang*' 'developer/gcc*'
NAME (PUBLISHER)                                  VERSION                    IFO
developer/gcc11                                   11.3.0-151044.0            im-
developer/gcc12                                   12.2.0-151044.0            im-
ooce/developer/clang-111 (extra.omnios)           11.1.0-151040.0            im-
ooce/developer/clang-13 (extra.omnios)            13.0.1-151044.0            im-
ooce/developer/clang-14 (extra.omnios)            14.0.6-151044.0            im-
ooce/developer/clang-15 (extra.omnios)            15.0.3-151044.0            im-
```

**Comment by infrastation** [comment]
Thank you very much, I confirm the fix, `illumos-amd64` has been reconfigured to use GCC 12 and Clang 15 for all projects. As a useful by-product of this, libpcap and tcpdump builds now emit a couple new warnings (they were not warning-free on illimos, so this does not fail the build).
